version: '3'
services:
  app:
    image: app-tracer
    build:
      context: ./
      dockerfile: ./dockerfile
    command: 'npm run start-restify'
    environment:
      JAEGER_SERVICE_NAME: "Meu_Servico"
      JAEGER_SERVICE_VERSION: "1.0.0"
      JAEGER_SAMPLER_TYPE: "probabilistic"
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6832
    volumes:
      - .:/app
    networks:
      - jaeger-net
    ports:
      - "3000:3000"
      - "9222:9222"
  jaeger:
    image: jaegertracing/all-in-one:1.8
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - jaeger-net
    expose:
      - "9411"
      - "16686"
      - "6832/udp"
      - "5775/udp"
      - "6831/udp"
      - "5778"
      - "14268"
    ports:
      - "9411:9411"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
networks: 
  jaeger-net: 
    driver: bridge
    ipam: 
      config: 
      - subnet: 192.192.128.0/24